use_frameworks!

platform :ios, '8.0'

target 'KYUtil_Example' do
  pod 'KYUtil', :path => '../'

  target 'KYUtil_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
