use_frameworks!

platform :ios, '9.0'

target 'KYUtil_Example' do
  pod 'KYUtil', :path => '../', :subspecs => [
    'KYCategories',
    'KYPathUtil',
  ]

  target 'KYUtil_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
